---
repos:
  - repo: local
    hooks:
      - id: format
        name: Format python scripts with black
        entry: make format
        language: system
      - id: check
        name: Check formatting and linter
        entry: make lint
        language: system
